backend:
  name: github
  repo: ubillanibal/portfolio-anibal
  branch: main
  base_url: https://my-portfolio.ubilla-anibal.workers.dev
  auth_endpoint: /api/auth

media_folder: public/images
public_folder: /images

collections:
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: text}
      - {label: Publish Date, name: pubDate, widget: datetime}
      - {label: Hero Image, name: heroImage, widget: image, required: false}
      - {label: Tags, name: tags, widget: list, required: false}
      - {label: Live URL, name: liveUrl, widget: string, required: false}
      - {label: Repo URL, name: repoUrl, widget: string, required: false}
      - {label: Body, name: body, widget: markdown}
